service: world-dom-backend

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  environment:
    GAME_TABLE: ${self:service}-game
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:PutItem
            - dynamodb:GetItem
            - dynamodb:DeleteItem
            - dynamodb:UpdateItem
            - dynamodb:Query
          Resource: 
            - !GetAtt GameTable.Arn
            - !Join ['', [!GetAtt GameTable.Arn, '/index/GSI1']]
        - Effect: Allow
          Action:
            - execute-api:ManageConnections
          Resource: !Sub 'arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:*/*/@connections/*'

custom:
  serverless-offline:
    httpPort: 3000
    websocketPort: 3001

functions:
  connect:
    handler: handlers/connect.handler
    events:
      - websocket:
          route: $connect
  disconnect:
    handler: handlers/disconnect.handler
    events:
      - websocket:
          route: $disconnect
  message:
    handler: handlers/message.handler
    events:
      - websocket:
          route: $default

resources:
  Resources:
    GameTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.GAME_TABLE}
        AttributeDefinitions:
          - AttributeName: PK
            AttributeType: S
          - AttributeName: SK
            AttributeType: S
          - AttributeName: GSI1PK
            AttributeType: S
          - AttributeName: GSI1SK
            AttributeType: S
        KeySchema:
          - AttributeName: PK
            KeyType: HASH
          - AttributeName: SK
            KeyType: RANGE
        GlobalSecondaryIndexes:
          - IndexName: GSI1
            KeySchema:
              - AttributeName: GSI1PK
                KeyType: HASH
              - AttributeName: GSI1SK
                KeyType: RANGE
            Projection:
              ProjectionType: INCLUDE
              NonKeyAttributes:
                - PK
                - SK
                - username
        BillingMode: PAY_PER_REQUEST
        TimeToLiveSpecification:
          AttributeName: ttl
          Enabled: true