export const COUNTRIES = {
  "AF": { name: "Afghanistan", capital: "Kabul" },
  "AL": { name: "Albania", capital: "Tirana" },
  "DZ": { name: "Algeria", capital: "Algiers" },
  "AD": { name: "Andorra", capital: "Andorra la Vella" },
  "AO": { name: "Angola", capital: "Luanda" },
  "AG": { name: "Antigua and Barbuda", capital: "St. John's" },
  "AR": { name: "Argentina", capital: "Buenos Aires" },
  "AM": { name: "Armenia", capital: "Yerevan" },
  "AU": { name: "Australia", capital: "Canberra" },
  "AT": { name: "Austria", capital: "Vienna" },
  "AZ": { name: "Azerbaijan", capital: "Baku" },
  "BH": { name: "Bahrain", capital: "Manama" },
  "BD": { name: "Bangladesh", capital: "Dhaka" },
  "BB": { name: "Barbados", capital: "Bridgetown" },
  "BY": { name: "Belarus", capital: "Minsk" },
  "BE": { name: "Belgium", capital: "Brussels" },
  "BZ": { name: "Belize", capital: "Belmopan" },
  "BJ": { name: "Benin", capital: "Porto-Novo" },
  "BT": { name: "Bhutan", capital: "Thimphu" },
  "BO": { name: "Bolivia", capital: "La Paz" },
  "BA": { name: "Bosnia and Herzegovina", capital: "Sarajevo" },
  "BW": { name: "Botswana", capital: "Gaborone" },
  "BR": { name: "Brazil", capital: "Brasília" },
  "BN": { name: "Brunei", capital: "Bandar Seri Begawan" },
  "BG": { name: "Bulgaria", capital: "Sofia" },
  "BF": { name: "Burkina Faso", capital: "Ouagadougou" },
  "BI": { name: "Burundi", capital: "Gitega" },
  "CV": { name: "Cabo Verde", capital: "Praia" },
  "KH": { name: "Cambodia", capital: "Phnom Penh" },
  "CM": { name: "Cameroon", capital: "Yaoundé" },
  "CA": { name: "Canada", capital: "Ottawa" },
  "CF": { name: "Central African Republic", capital: "Bangui" },
  "TD": { name: "Chad", capital: "N'Djamena" },
  "CL": { name: "Chile", capital: "Santiago" },
  "CN": { name: "China", capital: "Beijing" },
  "CO": { name: "Colombia", capital: "Bogotá" },
  "KM": { name: "Comoros", capital: "Moroni" },
  "CG": { name: "Congo", capital: "Brazzaville" },
  "CR": { name: "Costa Rica", capital: "San José" },
  "HR": { name: "Croatia", capital: "Zagreb" },
  "CU": { name: "Cuba", capital: "Havana" },
  "CY": { name: "Cyprus", capital: "Nicosia" },
  "CZ": { name: "Czech Republic", capital: "Prague" },
  "DK": { name: "Denmark", capital: "Copenhagen" },
  "DJ": { name: "Djibouti", capital: "Djibouti" },
  "DM": { name: "Dominica", capital: "Roseau" },
  "DO": { name: "Dominican Republic", capital: "Santo Domingo" },
  "EC": { name: "Ecuador", capital: "Quito" },
  "EG": { name: "Egypt", capital: "Cairo" },
  "SV": { name: "El Salvador", capital: "San Salvador" },
  "GQ": { name: "Equatorial Guinea", capital: "Malabo" },
  "ER": { name: "Eritrea", capital: "Asmara" },
  "EE": { name: "Estonia", capital: "Tallinn" },
  "SZ": { name: "Eswatini", capital: "Mbabane" },
  "ET": { name: "Ethiopia", capital: "Addis Ababa" },
  "FJ": { name: "Fiji", capital: "Suva" },
  "FI": { name: "Finland", capital: "Helsinki" },
  "FR": { name: "France", capital: "Paris" },
  "GA": { name: "Gabon", capital: "Libreville" },
  "GM": { name: "Gambia", capital: "Banjul" },
  "GE": { name: "Georgia", capital: "Tbilisi" },
  "DE": { name: "Germany", capital: "Berlin" },
  "GH": { name: "Ghana", capital: "Accra" },
  "GR": { name: "Greece", capital: "Athens" },
  "GD": { name: "Grenada", capital: "St. George's" },
  "GT": { name: "Guatemala", capital: "Guatemala City" },
  "GN": { name: "Guinea", capital: "Conakry" },
  "GW": { name: "Guinea-Bissau", capital: "Bissau" },
  "GY": { name: "Guyana", capital: "Georgetown" },
  "HT": { name: "Haiti", capital: "Port-au-Prince" },
  "HN": { name: "Honduras", capital: "Tegucigalpa" },
  "HU": { name: "Hungary", capital: "Budapest" },
  "IS": { name: "Iceland", capital: "Reykjavik" },
  "IN": { name: "India", capital: "New Delhi" },
  "ID": { name: "Indonesia", capital: "Jakarta" },
  "IR": { name: "Iran", capital: "Tehran" },
  "IQ": { name: "Iraq", capital: "Baghdad" },
  "IE": { name: "Ireland", capital: "Dublin" },
  "IL": { name: "Israel", capital: "Jerusalem" },
  "IT": { name: "Italy", capital: "Rome" },
  "JM": { name: "Jamaica", capital: "Kingston" },
  "JP": { name: "Japan", capital: "Tokyo" },
  "JO": { name: "Jordan", capital: "Amman" },
  "KZ": { name: "Kazakhstan", capital: "Nur-Sultan" },
  "KE": { name: "Kenya", capital: "Nairobi" },
  "KI": { name: "Kiribati", capital: "Tarawa" },
  "KP": { name: "Korea, North", capital: "Pyongyang" },
  "KR": { name: "Korea, South", capital: "Seoul" },
  "XK": { name: "Kosovo", capital: "Pristina" },
  "KW": { name: "Kuwait", capital: "Kuwait City" },
  "KG": { name: "Kyrgyzstan", capital: "Bishkek" },
  "LA": { name: "Laos", capital: "Vientiane" },
  "LV": { name: "Latvia", capital: "Riga" },
  "LB": { name: "Lebanon", capital: "Beirut" },
  "LS": { name: "Lesotho", capital: "Maseru" },
  "LR": { name: "Liberia", capital: "Monrovia" },
  "LY": { name: "Libya", capital: "Tripoli" },
  "LI": { name: "Liechtenstein", capital: "Vaduz" },
  "LT": { name: "Lithuania", capital: "Vilnius" },
  "LU": { name: "Luxembourg", capital: "Luxembourg City" },
  "MG": { name: "Madagascar", capital: "Antananarivo" },
  "MW": { name: "Malawi", capital: "Lilongwe" },
  "MY": { name: "Malaysia", capital: "Kuala Lumpur" },
  "MV": { name: "Maldives", capital: "Malé" },
  "ML": { name: "Mali", capital: "Bamako" },
  "MT": { name: "Malta", capital: "Valletta" },
  "MH": { name: "Marshall Islands", capital: "Majuro" },
  "MR": { name: "Mauritania", capital: "Nouakchott" },
  "MU": { name: "Mauritius", capital: "Port Louis" },
  "MX": { name: "Mexico", capital: "Mexico City" },
  "FM": { name: "Micronesia", capital: "Palikir" },
  "MD": { name: "Moldova", capital: "Chișinău" },
  "MC": { name: "Monaco", capital: "Monaco" },
  "MN": { name: "Mongolia", capital: "Ulan Bator" },
  "ME": { name: "Montenegro", capital: "Podgorica" },
  "MA": { name: "Morocco", capital: "Rabat" },
  "MZ": { name: "Mozambique", capital: "Maputo" },
  "MM": { name: "Myanmar", capital: "Naypyidaw" },
  "NA": { name: "Namibia", capital: "Windhoek" },
  "NR": { name: "Nauru", capital: "Yaren District" },
  "NP": { name: "Nepal", capital: "Kathmandu" },
  "NL": { name: "Netherlands", capital: "Amsterdam" },
  "NZ": { name: "New Zealand", capital: "Wellington" },
  "NI": { name: "Nicaragua", capital: "Managua" },
  "NE": { name: "Niger", capital: "Niamey" },
  "NG": { name: "Nigeria", capital: "Abuja" },
  "MK": { name: "North Macedonia", capital: "Skopje" },
  "NO": { name: "Norway", capital: "Oslo" },
  "OM": { name: "Oman", capital: "Muscat" },
  "PK": { name: "Pakistan", capital: "Islamabad" },
  "PW": { name: "Palau", capital: "Ngerulmud" },
  "PS": { name: "Palestine", capital: "East Jerusalem" },
  "PA": { name: "Panama", capital: "Panama City" },
  "PG": { name: "Papua New Guinea", capital: "Port Moresby" },
  "PY": { name: "Paraguay", capital: "Asunción" },
  "PE": { name: "Peru", capital: "Lima" },
  "PH": { name: "Philippines", capital: "Manila" },
  "PL": { name: "Poland", capital: "Warsaw" },
  "PT": { name: "Portugal", capital: "Lisbon" },
  "QA": { name: "Qatar", capital: "Doha" },
  "RO": { name: "Romania", capital: "Bucharest" },
  "RU": { name: "Russia", capital: "Moscow" },
  "RW": { name: "Rwanda", capital: "Kigali" },
  "KN": { name: "Saint Kitts and Nevis", capital: "Basseterre" },
  "LC": { name: "Saint Lucia", capital: "Castries" },
  "VC": { name: "Saint Vincent and the Grenadines", capital: "Kingstown" },
  "WS": { name: "Samoa", capital: "Apia" },
  "SM": { name: "San Marino", capital: "San Marino" },
  "ST": { name: "Sao Tome and Principe", capital: "São Tomé" },
  "SA": { name: "Saudi Arabia", capital: "Riyadh" },
  "SN": { name: "Senegal", capital: "Dakar" },
  "RS": { name: "Serbia", capital: "Belgrade" },
  "SC": { name: "Seychelles", capital: "Victoria" },
  "SL": { name: "Sierra Leone", capital: "Freetown" },
  "SG": { name: "Singapore", capital: "Singapore" },
  "SK": { name: "Slovakia", capital: "Bratislava" },
  "SI": { name: "Slovenia", capital: "Ljubljana" },
  "SB": { name: "Solomon Islands", capital: "Honiara" },
  "SO": { name: "Somalia", capital: "Mogadishu" },
  "ZA": { name: "South Africa", capital: "Pretoria" },
  "SS": { name: "South Sudan", capital: "Juba" },
  "ES": { name: "Spain", capital: "Madrid" },
  "LK": { name: "Sri Lanka", capital: "Colombo" },
  "SD": { name: "Sudan", capital: "Khartoum" },
  "SR": { name: "Suriname", capital: "Paramaribo" },
  "SE": { name: "Sweden", capital: "Stockholm" },
  "CH": { name: "Switzerland", capital: "Bern" },
  "SY": { name: "Syria", capital: "Damascus" },
  "TW": { name: "Taiwan", capital: "Taipei" },
  "TJ": { name: "Tajikistan", capital: "Dushanbe" },
  "TZ": { name: "Tanzania", capital: "Dodoma" },
  "TH": { name: "Thailand", capital: "Bangkok" },
  "TL": { name: "Timor-Leste", capital: "Dili" },
  "TG": { name: "Togo", capital: "Lomé" },
  "TO": { name: "Tonga", capital: "Nuku'alofa" },
  "TT": { name: "Trinidad and Tobago", capital: "Port of Spain" },
  "TN": { name: "Tunisia", capital: "Tunis" },
  "TR": { name: "Turkey", capital: "Ankara" },
  "TM": { name: "Turkmenistan", capital: "Ashgabat" },
  "TV": { name: "Tuvalu", capital: "Funafuti" },
  "UG": { name: "Uganda", capital: "Kampala" },
  "UA": { name: "Ukraine", capital: "Kyiv" },
  "AE": { name: "United Arab Emirates", capital: "Abu Dhabi" },
  "GB": { name: "United Kingdom", capital: "London" },
  "US": { name: "United States", capital: "Washington, D.C." },
  "UY": { name: "Uruguay", capital: "Montevideo" },
  "UZ": { name: "Uzbekistan", capital: "Tashkent" },
  "VU": { name: "Vanuatu", capital: "Port Vila" },
  "VA": { name: "Vatican City", capital: "Vatican City" },
  "VE": { name: "Venezuela", capital: "Caracas" },
  "VN": { name: "Vietnam", capital: "Hanoi" },
  "YE": { name: "Yemen", capital: "Sana'a" },
  "ZM": { name: "Zambia", capital: "Lusaka" },
  "ZW": { name: "Zimbabwe", capital: "Harare" },
  "HK": { name: "Hong Kong", capital: "Hong Kong" },
  "MO": { name: "Macau", capital: "Macau" },
  "NC": { name: "New Caledonia", capital: "Nouméa" },
  "AI": { name: "Anguilla", capital: "The Valley" },
  "AS": { name: "American Samoa", capital: "Pago Pago" },
  "AW": { name: "Aruba", capital: "Oranjestad" },
  "AX": { name: "Åland Islands", capital: "Mariehamn" },
  "BL": { name: "Saint Barthélemy", capital: "Gustavia" },
  "BQ": { name: "Bonaire, Sint Eustatius and Saba", capital: "Kralendijk" },
  "BS": { name: "Bahamas", capital: "Nassau" },
  "EH": { name: "Western Sahara", capital: "El Aaiún" },
  "GG": { name: "Guernsey", capital: "St. Peter Port" },
  "GI": { name: "Gibraltar", capital: "Gibraltar" },
  "GL": { name: "Greenland", capital: "Nuuk" },
  "GP": { name: "Guadeloupe", capital: "Basse-Terre" },
  "GU": { name: "Guam", capital: "Hagåtña" },
  "IM": { name: "Isle of Man", capital: "Douglas" },
  "JE": { name: "Jersey", capital: "St. Helier" },
  "KY": { name: "Cayman Islands", capital: "George Town" },
  "MC": { name: "Monaco", capital: "Monaco" },
  "MP": { name: "Northern Mariana Islands", capital: "Saipan" },
  "MQ": { name: "Martinique", capital: "Fort-de-France" },
  "MS": { name: "Montserrat", capital: "Plymouth" },
  "NU": { name: "Niue", capital: "Alofi" },
  "PF": { name: "French Polynesia", capital: "Papeete" },
  "PM": { name: "Saint Pierre and Miquelon", capital: "Saint-Pierre" },
  "PN": { name: "Pitcairn", capital: "Adamstown" },
  "PR": { name: "Puerto Rico", capital: "San Juan" },
  "RE": { name: "Réunion", capital: "Saint-Denis" },
  "SX": { name: "Sint Maarten", capital: "Philipsburg" },
  "TC": { name: "Turks and Caicos Islands", capital: "Cockburn Town" },
  "TF": { name: "French Southern Territories", capital: "N/A" },
  "TK": { name: "Tokelau", capital: "N/A" },
  "UM": { name: "United States Minor Outlying Islands", capital: "N/A" },
  "VG": { name: "British Virgin Islands", capital: "Road Town" },
  "VI": { name: "U.S. Virgin Islands", capital: "Charlotte Amalie" },
  "KZ": { name: "Kazakhstan", capital: "Astana" },
}; 